const menu = [
    {
      id: 1,
      title: 'pav bhaji',
      category: 'breakfast',
      price: 100,
      img: 'https://cdn.tasteatlas.com//Images/Dishes/081e0170e376406aa4b56f5b86cc3156.jpg?w=905&h=510',
      desc: `It consists of a vegetable curry that is typically served with a soft bread roll known as pav.`,
    },
    {
      id: 2,
      title: 'masala dosa',
      category: 'lunch',
      price:50,
      img: 'https://cdn.tasteatlas.com//Images/Dishes/ba7bab747c7e41769dbc895a84626a23.jpg?w=905&h=510',
      desc: ` made from a batter of soaked rice and lentils that is baked into a thin pancake and usually stuffed with potatoes, onions, and mustard seeds. `,
    },
    {
      id: 3,
      title: 'palak panner',
      category: 'shakes',
      price: 70,
      img: 'https://cdn.tasteatlas.com//Images/Dishes/4ecba690cc0b47809d43d70c7a6b3a39.jpg?w=905&h=510',
      desc: ` paneer cheese in a rich, thick sauce consisting of puréed spinach mixed with tomatoes, garam masala, garlic, and numerous spices.`,
    },
    {
      id: 4,
      title: 'paani puri',
      category: 'breakfast',
      price:10,
      img: 'https://cdn.tasteatlas.com//Images/Dishes/b01fa4c9920d42df9ef472fd4f8e6fda.jpg?w=905&h=510',
      desc: ` it consists of a hollow puri that is fried until crispy, then stuffed with a combination of flavored water.`,
    },
    {
      id: 5,
      title: 'chaat',
      category: 'lunch',
      price:60,
      img: 'https://cdn.tasteatlas.com//Images/Dishes/84327074df8e4c5fabeaeca6fa3ab659.jpg?w=905&h=510',
      desc: ` Indian street foods, snacks, or small meals which usually combine salty, spicy, sweet, and sour flavors`,
    },
    {
      id: 6,
      title: 'upamaa',
      category: 'shakes',
      price:30,
      img: 'https://cdn.tasteatlas.com//Images/Dishes/e4e3193046014f5bb9d0b6dc838d0f53.jpg?w=905&h=510',
      desc: `Upma is a wholesome Indian dish made with dry semolina or rice flour, cooked into a thick porridge.`,
    },
    {
      id: 7,
      title: 'vada paav',
      category: 'breakfast',
      price:40,
      img: 'https://cdn.tasteatlas.com//Images/Dishes/951728fa0ae74174a2602aaece17368c.jpg?w=905&h=510',
      desc: `vada, or spicy mashed potatoes that are deep-fried in chickpea batter, and pav, or white bread rolls `,
    },
    {
      id: 8,
      title: 'samosa',
      category: 'lunch',
      price:25,
      img: 'https://cdn.tasteatlas.com//Images/Dishes/e668e32ae1a3423c95fbd4d77f8c940c.jpg?w=905&h=510',
      desc: `These deep-fried, triangular pastries are filled with onions, lentils, spiced potatoes, peas. `,
    },
    {
      id: 9,
      title: 'idli',
      category: 'shakes',
      price:150,
      img: 'https://cdn.tasteatlas.com//Images/Dishes/7389072b562f4dd6b08608b2692b4728.jpg?w=905&h=510',
      desc: `These savory cakes are commonly served hot and consumed on their own, dipped into sambar or chutneys, or seasoned with numerous spice.`,
    },
    {
      id: 10,
      title: 'naan',
      category: 'lunch',
      price: 35,
      img:"https://cdn.tasteatlas.com//images/dishes/8f5e5f67af2541ac8008637115b7c104.jpg?w=905&h=510",
      desc: `These savory cakes are commonly served hot and consumed on their own, dipped into sambar or chutneys, or seasoned with numerous spice.`,
    },
  ];
  export default menu;